-- Crewline schema v40 — office accounts can no longer forge a worker's chat
-- messages.
--
-- Run after schema_v2.sql. Safe to re-run.
--
-- messages_office_write (schema_v2.sql, generated by the do-block loop that
-- gives office roles "for all" on assignments/site_files/.../messages) only
-- ever checked company_id and current_is_office() — never author_id. That
-- policy exists so the office can post system/announcement rows and manage
-- the table generally, but combined with messages_field_insert (which does
-- constrain author_id = current_worker_id(), for non-office field accounts)
-- it left a real gap: any office session could insert, or update, a
-- kind='user' row with author_id set to any worker in the company, and the
-- Chat tab renders it as an ordinary bubble under that worker's name with no
-- indication it wasn't theirs. Postgres OR's multiple permissive policies
-- together, so tightening messages_field_insert would not have helped —
-- messages_office_write was the one actually granting the write.
--
-- Fixed by replacing messages_office_write, for the messages table only,
-- with a version whose WITH CHECK also requires kind <> 'user' or
-- author_id = current_worker_id(). System rows (kind='system') and updates
-- that don't touch author_id/kind are unaffected; office staff still can't
-- claim to be a specific worker when posting as themselves in a job chat.
-- USING is left as the original office_write clause — read visibility is
-- already governed by messages_read, and office still needs to see/delete
-- any row to moderate a channel.

drop policy if exists messages_office_write on messages;
create policy messages_office_write on messages
  for all
  using (company_id = current_company_id() and current_is_office())
  with check (
    company_id = current_company_id() and current_is_office()
    and (kind <> 'user' or author_id = current_worker_id())
  );
