/**
 * Reading a builder's programme out of a spreadsheet, with no dependencies.
 *
 * A construction programme arrives as an Excel export or a CSV about as often
 * as it arrives as a PDF, and those two are structured data that should never
 * need an AI call or a paid library to read. SheetJS is 400 kB and this app
 * ships one bundle to people on 4G in a ute; the whole of what is needed here
 * is a zip reader and enough of SpreadsheetML to pull a grid of strings out.
 *
 * .xlsx is a ZIP of XML, and both halves are small problems:
 *   * DecompressionStream('deflate-raw') has been in every current browser
 *     since 2023 and inflates the raw deflate streams a zip stores.
 *   * The XML is scanned for the six tags that matter rather than parsed with
 *     DOMParser, which is browser-only and would make this untestable.
 *
 * What this deliberately does NOT do: formulas, styles, merged cells, charts.
 * A programme is a grid of text and dates. Anything cleverer than that belongs
 * in a real library, and needing one would be a sign the input is wrong.
 */

/** A sheet as rows of trimmed strings. Ragged: rows are only as long as they are. */
export interface Grid {
  name: string
  rows: string[][]
}

// ------------------------------------------------------------------ the zip

interface ZipEntry {
  name: string
  bytes: Uint8Array
}

const LOCAL_SIG = 0x04034b50
const CD_SIG = 0x02014b50
const EOCD_SIG = 0x06054b50

/**
 * Entries out of a zip, read from the central directory rather than by walking
 * local headers. Walking forwards works right up until an entry uses a data
 * descriptor (sizes written AFTER the data, which streaming writers do), at
 * which point the local header's size fields are zero and the walk desyncs.
 * Excel's own writer does exactly that.
 */
async function unzip(buf: ArrayBuffer): Promise<ZipEntry[]> {
  const view = new DataView(buf)
  const all = new Uint8Array(buf)

  // The end-of-central-directory record is at the tail, after a comment of
  // unknown length, so it is found by scanning backwards for its signature.
  let eocd = -1
  for (let i = all.length - 22; i >= 0 && i > all.length - 65_558; i--) {
    if (view.getUint32(i, true) === EOCD_SIG) {
      eocd = i
      break
    }
  }
  if (eocd < 0) throw new Error('Not a zip file — is this really an .xlsx?')

  const count = view.getUint16(eocd + 10, true)
  let p = view.getUint32(eocd + 16, true)

  const out: ZipEntry[] = []
  for (let i = 0; i < count; i++) {
    if (view.getUint32(p, true) !== CD_SIG) break
    const method = view.getUint16(p + 10, true)
    const compressedSize = view.getUint32(p + 20, true)
    const nameLen = view.getUint16(p + 28, true)
    const extraLen = view.getUint16(p + 30, true)
    const commentLen = view.getUint16(p + 32, true)
    const localAt = view.getUint32(p + 42, true)
    const name = new TextDecoder().decode(all.subarray(p + 46, p + 46 + nameLen))
    p += 46 + nameLen + extraLen + commentLen

    if (view.getUint32(localAt, true) !== LOCAL_SIG) continue
    // The local header's own name and extra lengths are authoritative for where
    // the data starts — the central directory's extra field is a different one.
    const lNameLen = view.getUint16(localAt + 26, true)
    const lExtraLen = view.getUint16(localAt + 28, true)
    const start = localAt + 30 + lNameLen + lExtraLen
    const raw = all.subarray(start, start + compressedSize)

    if (method === 0) {
      out.push({ name, bytes: raw })
    } else if (method === 8) {
      out.push({ name, bytes: await inflateRaw(raw) })
    }
    // Any other method (bzip2, lzma) is not something Excel writes; skipped.
  }
  return out
}

async function inflateRaw(bytes: Uint8Array): Promise<Uint8Array> {
  if (typeof DecompressionStream === 'undefined') {
    throw new Error('This browser cannot read .xlsx files. Export the programme as CSV instead.')
  }
  const ds = new DecompressionStream('deflate-raw')
  // A fresh copy: the subarray is a view onto the whole file, and Blob would
  // otherwise take the entire buffer.
  const stream = new Blob([new Uint8Array(bytes)]).stream().pipeThrough(ds)
  return new Uint8Array(await new Response(stream).arrayBuffer())
}

// ---------------------------------------------------------------- the sheet

const text = (b: Uint8Array) => new TextDecoder().decode(b)

/**
 * A scanner for the handful of SpreadsheetML tags this needs, rather than
 * DOMParser.
 *
 * DOMParser is browser-only: it does not exist in Node, which makes anything
 * built on it impossible to unit test, and it is absent in a worker too. The
 * XML in an .xlsx is machine-generated by Excel and structurally boring —
 * `<c r="B3" t="s"><v>4</v></c>` — so scanning it is both simpler and more
 * portable than pulling in a DOM.
 */
interface Tag {
  attrs: Record<string, string>
  /** Text between this tag and its close. Empty for a self-closing tag. */
  inner: string
}

const XML_ENTITIES: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
}

function unescapeXml(s: string): string {
  if (!s.includes('&')) return s
  return s.replace(/&(#x?[0-9a-fA-F]+|[a-z]+);/g, (whole, body: string) => {
    if (body[0] === '#') {
      const code = body[1] === 'x' || body[1] === 'X' ? parseInt(body.slice(2), 16) : parseInt(body.slice(1), 10)
      return Number.isFinite(code) ? String.fromCodePoint(code) : whole
    }
    return XML_ENTITIES[body] ?? whole
  })
}

function parseAttrs(raw: string): Record<string, string> {
  const out: Record<string, string> = {}
  for (const m of raw.matchAll(/([\w:]+)\s*=\s*"([^"]*)"/g)) out[m[1]] = unescapeXml(m[2])
  return out
}

/**
 * Every `<name …>` element at any depth, with its inner text. Nesting of the
 * SAME tag is not handled and does not occur in SpreadsheetML — a row never
 * contains a row.
 */
function tags(xml: string, name: string): Tag[] {
  const out: Tag[] = []
  const open = new RegExp(`<${name}(\\s[^>]*?)?(/?)>`, 'g')
  let m: RegExpExecArray | null
  while ((m = open.exec(xml))) {
    const attrs = parseAttrs(m[1] ?? '')
    if (m[2] === '/') {
      out.push({ attrs, inner: '' })
      continue
    }
    const closeAt = xml.indexOf(`</${name}>`, open.lastIndex)
    if (closeAt < 0) break
    out.push({ attrs, inner: xml.slice(open.lastIndex, closeAt) })
    open.lastIndex = closeAt + name.length + 3
  }
  return out
}

/** The text of every `<t>` in a fragment — rich text splits one string across runs. */
const innerText = (xml: string) => tags(xml, 't').map((t) => unescapeXml(t.inner)).join('')

/**
 * Excel serial date → ISO. Day 1 is 1900-01-01, and the format deliberately
 * contains a leap day that never existed (1900 was not a leap year) for
 * compatibility with Lotus 1-2-3, so the epoch is offset by two days. Dates
 * before March 1900 come out a day wrong; no construction programme has one.
 */
function serialToIso(serial: number): string | null {
  if (!Number.isFinite(serial) || serial < 20 || serial > 100_000) return null
  const ms = Math.round((serial - 25_569) * 86_400_000)
  const d = new Date(ms)
  return Number.isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10)
}

function colIndex(ref: string): number {
  // "BC12" -> 54. Base-26 with no zero, which is why it is a loop and not a
  // lookup: 'A'..'Z' then 'AA', and there is no digit worth zero.
  let n = 0
  for (const ch of ref) {
    const c = ch.charCodeAt(0)
    if (c < 65 || c > 90) break
    n = n * 26 + (c - 64)
  }
  return n - 1
}

/** Every sheet in an .xlsx, as grids of strings. */
export async function readXlsx(buf: ArrayBuffer): Promise<Grid[]> {
  const entries = await unzip(buf)
  const byName = new Map(entries.map((e) => [e.name, e.bytes]))

  // Shared strings: Excel stores repeated text once and references it by index.
  const sst = byName.get('xl/sharedStrings.xml')
  const shared = sst ? tags(text(sst), 'si').map((si) => innerText(si.inner)) : []

  // Sheet names live in the workbook, in document order, which matches the
  // sheetN.xml ordering closely enough to label them usefully.
  const wb = byName.get('xl/workbook.xml')
  const names = wb ? tags(text(wb), 'sheet').map((sh) => sh.attrs.name ?? '') : []

  const sheetFiles = entries
    .filter((e) => /^xl\/worksheets\/sheet\d+\.xml$/.test(e.name))
    .sort((a, b) => {
      const n = (s: string) => Number(s.match(/sheet(\d+)\.xml$/)?.[1] ?? 0)
      return n(a.name) - n(b.name)
    })

  const grids: Grid[] = []
  for (let i = 0; i < sheetFiles.length; i++) {
    const xml = text(sheetFiles[i].bytes)
    const rows: string[][] = []

    for (const row of tags(xml, 'row')) {
      const cells: string[] = []
      for (const c of tags(row.inner, 'c')) {
        const at = colIndex(c.attrs.r ?? '')
        const type = c.attrs.t
        let value = ''

        if (type === 'inlineStr') {
          value = innerText(c.inner)
        } else {
          const v = tags(c.inner, 'v')[0]?.inner ?? ''
          if (type === 's') {
            value = shared[Number(v)] ?? ''
          } else if (v !== '') {
            // A date is a number with a date format applied. Reading the style
            // table to find out which is a lot of machinery for a guess; a bare
            // number in a programme's date range is almost always a date, and
            // the import screen shows every value for confirmation anyway.
            const iso = /^\d+(\.\d+)?$/.test(v) ? serialToIso(Number(v)) : null
            value = iso ?? v
          }
        }

        if (at >= 0) {
          while (cells.length < at) cells.push('')
          cells[at] = value.trim()
        } else {
          cells.push(value.trim())
        }
      }
      rows.push(cells)
    }

    grids.push({ name: names[i] || `Sheet ${i + 1}`, rows })
  }
  return grids
}

// ------------------------------------------------------------------ the csv

/**
 * RFC 4180 CSV: quoted fields, embedded commas and newlines, doubled quotes.
 * Hand-rolled because `split(',')` mangles the first address column it meets,
 * and a programme is full of "Level 2, east" style names.
 */
export function readCsv(input: string): string[][] {
  const rows: string[][] = []
  let row: string[] = []
  let field = ''
  let quoted = false

  // A BOM survives Excel's "Save as CSV" and turns the first header into
  // something that matches nothing.
  const s = input.charCodeAt(0) === 0xfeff ? input.slice(1) : input

  for (let i = 0; i < s.length; i++) {
    const ch = s[i]
    if (quoted) {
      if (ch === '"') {
        if (s[i + 1] === '"') {
          field += '"'
          i++
        } else {
          quoted = false
        }
      } else {
        field += ch
      }
      continue
    }
    if (ch === '"') {
      quoted = true
    } else if (ch === ',') {
      row.push(field.trim())
      field = ''
    } else if (ch === '\n') {
      row.push(field.trim())
      rows.push(row)
      row = []
      field = ''
    } else if (ch !== '\r') {
      field += ch
    }
  }
  if (field !== '' || row.length > 0) {
    row.push(field.trim())
    rows.push(row)
  }
  return rows
}

// ------------------------------------------------- making sense of the grid

export interface ProgrammeRow {
  ref: string
  name: string
  trade: string
  startsOn: string | null
  endsOn: string | null
  durationDays: number | null
  pctComplete: number | null
  isOurs: boolean
  isPredecessor: boolean
}

/**
 * Column names as they actually appear on the programmes builders export.
 * Microsoft Project, Asta Powerproject and every Excel Gantt template disagree
 * about all of them, so each is matched by any of its aliases.
 */
const HEADERS: Record<string, string[]> = {
  ref: ['id', 'ref', 'no', 'no.', 'line', 'task id', 'wbs', 'activity id', 'code', 'item'],
  name: ['name', 'task', 'task name', 'activity', 'activity name', 'description', 'work', 'title'],
  trade: ['trade', 'resource', 'resource names', 'contractor', 'subcontractor', 'responsible', 'who'],
  startsOn: ['start', 'start date', 'starts', 'early start', 'planned start', 'from', 'commence'],
  endsOn: ['finish', 'end', 'end date', 'finish date', 'ends', 'early finish', 'planned finish', 'to', 'complete'],
  durationDays: ['duration', 'days', 'dur', 'duration (days)'],
  pctComplete: ['%', '% complete', 'percent complete', 'progress', 'complete', '% done'],
}

/** Lines that are ours, and lines we wait on. Both are correctable by hand. */
const OURS = /\b(tile|tiling|tiler|waterproof|membrane|grout|screed and tile|wet area)\b/i
const PREDECESSOR =
  /\b(screed|render|set out|frame|plaster|gyprock|plumb(ing|er)?\s*rough|rough[- ]?in|slab|hob|substrate|falls)\b/i

function norm(s: string): string {
  return s.toLowerCase().replace(/[_\s]+/g, ' ').replace(/[^a-z0-9% .]/g, '').trim()
}

/** Anything that reads as a date, in the formats a programme actually uses. */
export function parseDate(raw: string): string | null {
  const v = raw.trim()
  if (!v) return null
  if (/^\d{4}-\d{2}-\d{2}$/.test(v)) return v

  // Australian order, always: 03/04/2026 is 3 April. This app is sold into one
  // country and guessing month-first would silently move a start date by months.
  const dmy = v.match(/^(\d{1,2})[/\-.](\d{1,2})[/\-.](\d{2,4})$/)
  if (dmy) {
    const [, d, m, y] = dmy
    const year = y.length === 2 ? 2000 + Number(y) : Number(y)
    const day = Number(d)
    const month = Number(m)
    if (month >= 1 && month <= 12 && day >= 1 && day <= 31) {
      return `${year}-${String(month).padStart(2, '0')}-${String(day).padStart(2, '0')}`
    }
    return null
  }

  // "12 Mar 26", "Mon 12 Mar 2026", "12-Mar-2026"
  const named = v.match(/(\d{1,2})[\s\-]([A-Za-z]{3,})[\s\-](\d{2,4})/)
  if (named) {
    const months = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
    const mi = months.indexOf(named[2].slice(0, 3).toLowerCase())
    if (mi >= 0) {
      const year = named[3].length === 2 ? 2000 + Number(named[3]) : Number(named[3])
      return `${year}-${String(mi + 1).padStart(2, '0')}-${String(Number(named[1])).padStart(2, '0')}`
    }
  }
  return null
}

/**
 * Find the header row and read the programme off the grid.
 *
 * The header is hunted for rather than assumed to be row 1, because a builder's
 * export almost always opens with a title block: project name, revision, a logo
 * row, then the actual columns four or five rows down.
 */
export function extractProgramme(grid: Grid): { rows: ProgrammeRow[]; headerRow: number; note: string } {
  let best = { row: -1, score: 0, map: {} as Record<string, number> }

  for (let r = 0; r < Math.min(grid.rows.length, 30); r++) {
    const cells = grid.rows[r].map(norm)
    const map: Record<string, number> = {}
    let score = 0
    for (const [key, aliases] of Object.entries(HEADERS)) {
      const at = cells.findIndex((c) => c !== '' && aliases.includes(c))
      if (at >= 0) {
        map[key] = at
        score++
      }
    }
    if (score > best.score) best = { row: r, score, map }
  }

  // A name column and at least one date is the minimum that can produce
  // anything useful. Below that, say so rather than importing rubbish.
  if (best.score < 2 || best.map.name === undefined || (best.map.startsOn === undefined && best.map.endsOn === undefined)) {
    return {
      rows: [],
      headerRow: -1,
      note: 'No task/start columns found. Needs a header row with a task name and a start or finish date.',
    }
  }

  const { map } = best
  const at = (cells: string[], key: string) => (map[key] === undefined ? '' : (cells[map[key]] ?? ''))

  const rows: ProgrammeRow[] = []
  for (let r = best.row + 1; r < grid.rows.length; r++) {
    const cells = grid.rows[r]
    const name = at(cells, 'name')
    if (!name) continue

    const starts = parseDate(at(cells, 'startsOn'))
    const ends = parseDate(at(cells, 'endsOn'))
    if (!starts && !ends) continue

    const durRaw = at(cells, 'durationDays').replace(/[^0-9.]/g, '')
    const pctRaw = at(cells, 'pctComplete').replace(/[^0-9.]/g, '')
    const trade = at(cells, 'trade')
    const haystack = `${name} ${trade}`

    rows.push({
      ref: at(cells, 'ref') || String(rows.length + 1),
      name,
      trade,
      startsOn: starts,
      endsOn: ends ?? starts,
      durationDays: durRaw ? Math.round(Number(durRaw)) : null,
      pctComplete: pctRaw ? Math.min(100, Number(pctRaw)) : null,
      isOurs: OURS.test(haystack),
      isPredecessor: !OURS.test(haystack) && PREDECESSOR.test(haystack),
    })
  }

  const ours = rows.filter((r) => r.isOurs).length
  return {
    rows,
    headerRow: best.row,
    note:
      rows.length === 0
        ? 'Found the header but no dated task rows under it.'
        : `${rows.length} dated tasks, ${ours} read as ours. Check the ticks before importing — everything that matters keys off them.`,
  }
}
