#!/usr/bin/env bash
#
# Produce an Apple distribution signing identity without a Mac.
#
# Every guide for this assumes Keychain Access, which assumes macOS. None of it
# is actually necessary: the developer portal takes a certificate signing
# request generated by any OpenSSL, and a .p12 is just the certificate Apple
# hands back stapled to the private key you already had. This script does both
# halves and prints the two GitHub secrets at the end.
#
#   ./scripts/ios-signing.sh csr                 # step 1 — before the portal
#   ./scripts/ios-signing.sh p12 ~/Downloads/distribution.cer   # step 3 — after
#   ./scripts/ios-signing.sh profile ~/Downloads/Crewline.mobileprovision
#
# Everything is written to ./ios-signing/, which is gitignored. The private key
# in there is the thing an attacker would need to sign software as you — keep it
# somewhere you would keep a password, and do not commit it.

set -euo pipefail

DIR="${IOS_SIGNING_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/ios-signing}"
KEY="$DIR/ios_distribution.key"
CSR="$DIR/ios_distribution.csr"
P12="$DIR/ios_distribution.p12"

# openssl 3 writes PKCS#12 files with AES-256 and PBKDF2 by default, and macOS's
# `security import` cannot read those — the job fails with an unhelpful
# "MAC verification failed". -legacy asks for the RC2/3DES container macOS
# expects. openssl 1.x has no such flag and already produces the old format.
legacy_flag() {
  if openssl pkcs12 -help 2>&1 | grep -q -- '-legacy'; then printf -- '-legacy'; fi
}

usage() {
  cat <<'TXT'
Usage:
  ios-signing.sh csr [email]
      Generates a 2048-bit RSA key and a certificate signing request.
      Upload the .csr at https://developer.apple.com/account/resources/certificates/add
      choosing "Apple Distribution". Download the .cer it gives you.

  ios-signing.sh p12 <path-to-distribution.cer> [password]
      Staples that certificate to the key from step 1 and prints
      IOS_DIST_CERT_P12_BASE64 and IOS_DIST_CERT_PASSWORD.

  ios-signing.sh profile <path-to-.mobileprovision>
      Prints IOS_PROVISIONING_PROFILE_BASE64, and checks the profile is an
      App Store one for app.crewline.worker before you find out in CI.
TXT
}

case "${1:-}" in

csr)
  mkdir -p "$DIR"
  chmod 700 "$DIR"
  email="${2:-}"
  if [ -z "$email" ]; then
    read -r -p "Apple ID email for the CSR: " email
  fi
  if [ -f "$KEY" ]; then
    echo "A key already exists at $KEY."
    echo "Reusing it — a second CSR against the same key is fine, and replacing"
    echo "the key would invalidate any certificate already issued from it."
  else
    openssl genrsa -out "$KEY" 2048
    chmod 600 "$KEY"
  fi
  openssl req -new -key "$KEY" -out "$CSR" \
    -subj "/emailAddress=${email}/CN=Crewline Distribution/C=AU"
  echo
  echo "Certificate signing request written to:"
  echo "  $CSR"
  echo
  echo "Next:"
  echo "  1. https://developer.apple.com/account/resources/certificates/add"
  echo "  2. Choose 'Apple Distribution' — NOT 'Apple Development'. TestFlight"
  echo "     uploads signed with a development certificate are rejected."
  echo "  3. Upload $CSR, download the .cer."
  echo "  4. ./scripts/ios-signing.sh p12 <that .cer>"
  ;;

p12)
  cer="${2:-}"
  [ -n "$cer" ] || { usage; exit 1; }
  [ -f "$cer" ] || { echo "No such file: $cer" >&2; exit 1; }
  [ -f "$KEY" ] || { echo "No private key at $KEY — run 'ios-signing.sh csr' first." >&2; exit 1; }

  pass="${3:-$(openssl rand -base64 18)}"

  # Apple hands back DER; PKCS#12 wants PEM.
  openssl x509 -inform DER -in "$cer" -out "$DIR/distribution.pem" -outform PEM

  subject=$(openssl x509 -in "$DIR/distribution.pem" -noout -subject)
  case "$subject" in
    *"Apple Distribution"*|*"iPhone Distribution"*) ;;
    *)
      echo "That certificate is not a distribution certificate:" >&2
      echo "  $subject" >&2
      echo "TestFlight will reject a build signed with it. Request an" >&2
      echo "'Apple Distribution' certificate instead." >&2
      exit 1
      ;;
  esac

  # shellcheck disable=SC2046
  openssl pkcs12 -export $(legacy_flag) \
    -inkey "$KEY" \
    -in "$DIR/distribution.pem" \
    -out "$P12" \
    -name "Apple Distribution" \
    -passout "pass:${pass}"
  chmod 600 "$P12"

  echo
  echo "$subject"
  echo "Expires: $(openssl x509 -in "$DIR/distribution.pem" -noout -enddate | cut -d= -f2)"
  echo
  echo "GitHub secret  IOS_DIST_CERT_PASSWORD"
  echo "$pass"
  echo
  echo "GitHub secret  IOS_DIST_CERT_P12_BASE64"
  openssl base64 -A -in "$P12"
  echo
  ;;

profile)
  prof="${2:-}"
  [ -n "$prof" ] || { usage; exit 1; }
  [ -f "$prof" ] || { echo "No such file: $prof" >&2; exit 1; }

  # A .mobileprovision is a CMS-signed plist. `security cms -D` is the macOS way
  # to open it; there is no macOS here, and the payload is plain XML sitting
  # between the signature blocks, so lifting it out is enough to check it.
  # Parsed with plistlib rather than sed: Apple puts key and value on separate
  # lines, anybody's hand-written fixture puts them on one, and a checker that
  # only reads one of those layouts is not a checker.
  python3 - "$prof" <<'PY'
import plistlib, sys

raw = open(sys.argv[1], 'rb').read()
start, end = raw.find(b'<?xml'), raw.find(b'</plist>')
if start == -1 or end == -1:
    sys.exit("Not a provisioning profile — there is no plist inside it.")
p = plistlib.loads(raw[start:end + 8])

appid = (p.get('Entitlements', {}) or {}).get('application-identifier') \
        or p.get('application-identifier', '')
print(f"Profile name: {p.get('Name', '(unnamed)')}")
print(f"Covers:       {appid}")
print(f"Expires:      {p.get('ExpirationDate', '(unknown)')}")

if not appid.endswith('.app.crewline.worker'):
    sys.exit(f"That profile is for {appid or 'no app id at all'}, not app.crewline.worker.")
if 'ProvisionedDevices' in p:
    sys.exit("That is a development profile — it lists specific devices. "
             "TestFlight needs an App Store distribution profile.")
PY

  echo
  echo "GitHub secret  IOS_PROVISIONING_PROFILE_BASE64"
  openssl base64 -A -in "$prof"
  echo
  ;;

*)
  usage
  exit 1
  ;;
esac
